name: sale_helper_zencillo
description: "Package to Sale Helper"
version: 1.1.2
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  intl: ^0.19.0
  oxidized: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
